export const data = [
    {
        id: "1",
        name: "Alarm Clock",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Alarm%20clock%20using%20Arduino/Images/SS-1.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Alarm%20clock%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "2",
        name: "Alternate LED Blinking",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Alternate%20LED%20Blinking/Images/alternate_led_blinking.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Alternate%20LED%20Blinking",
        type: "arduinoCard",
    },
    {
        id: "3",
        name: "Automated Hand Sanitizer",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Automated%20Hand%20Sanitizer%20Dispenser/Images/SS-1.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automated%20Hand%20Sanitizer%20Dispenser",
        type: "arduinoCard",
    },
    {
        id: "4",
        name: "Automated Water Pump for Plants",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Automated%20Water%20Pump%20for%20Plants/img/automatedWaterPump.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automated%20Water%20Pump%20for%20Plants",
        type: "arduinoCard",
    },
    {
        id: "5",
        name: "Automatic Door bell",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Automatic%20Door%20Bell/Images/preview1.jpg?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automatic%20Door%20Bell",
        type: "arduinoCard",
    },
    {
        id: "6",
        name: "Automatic Fan Speed Control",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Automatic%20Fan%20Speed%20Control/Images/preview1.jpg?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automatic%20Fan%20Speed%20Control",
        type: "arduinoCard",
    },
    {
        id: "7",
        name: "Automatic Room Temperature Controller",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Automatic%20Room%20Temperature%20Controller/Images/circuit_diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automatic%20Room%20Temperature%20Controller",
        type: "arduinoCard",
    },
    {
        id: "8",
        name: "Basic LED Blinking",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Basic%20LED%20Blinking%20Using%20Arduino/Images/Fritzing%20Circuit%20Diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Basic%20LED%20Blinking%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "9",
        name: "Battery Powered Step Counter",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Battery%20Powered%20Step%20Counter/Images/Circuit%20Diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Battery%20Powered%20Step%20Counter",
        type: "arduinoCard",
    },
    {
        id: "10",
        name: "Burglar Alarm",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Burglar%20Alarm/Images/preview1.jpg?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Burglar%20Alarm",
        type: "arduinoCard",
    },
    {
        id: "11",
        name: "Combination Lock",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Combination%20Lock%20using%20Arduino/Images/Circuit%20Diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Combination%20Lock%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "12",
        name: "Controlling DC Motor Using IR Remote",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Controlling%20DC%20Motor%20Using%20IR%20Remote/Images/circuit%20diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Controlling%20DC%20Motor%20Using%20IR%20Remote",
        type: "arduinoCard",
    },
    {
        id: "13",
        name: "Controlling LED using IR Remote",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Controlling%20LED%20using%20IR%20Remote/Images/Circuit%20Diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Controlling%20LED%20using%20IR%20Remote",
        type: "arduinoCard",
    },
    {
        id: "14",
        name: "Current Sensor",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Current%20Sensor%20Using%20Arduino/images/circuit_diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Current%20Sensor%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "15",
        name: "Dino Game",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Dino%20Game%20using%20Arduino/Images/Circuit%20Diagram.jpg?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Dino%20Game%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "16",
        name: "Display Time on LCD",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Display%20Time%20on%20LCD%20using%20Arduino/Images/Block%20Diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Display%20Time%20on%20LCD%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "17",
        name: "Dual Axis Solar Tracker",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Dual%20Axis%20Solar%20Tracker/Images/dual_axis_solar_tracker.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Dual%20Axis%20Solar%20Tracker",
        type: "arduinoCard",
    },
    {
        id: "18",
        name: "Electronic Voting Machine",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Electronic%20Voting%20Machine/images/circuit%20diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Electronic%20Voting%20Machine",
        type: "arduinoCard",
    },
    {
        id: "19",
        name: "Elevator Load Evaluation System",
        image: "",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Elevator%20Load%20Evaluation%20System%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "20",
        name: "Emergency Ventilator",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Emergency%20Ventilator/Images/SS-1.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Emergency%20Ventilator",
        type: "arduinoCard",
    },
    {
        id: "21",
        name: "Fire Alarm",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Fire%20Alarm%20using%20Arduino/Images/SS-1.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Fire%20Alarm%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "22",
        name: "Gas Leakage Detection",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Gas%20Leakage%20Detection/images/circuit_image.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Gas%20Leakage%20Detection",
        type: "arduinoCard",
    },
    {
        id: "23",
        name: "HEART-BEAT Sensor",
        image: "https://user-images.githubusercontent.com/98482003/198891469-9dce6218-cf3a-4ea9-ad4b-f2b425fb2aa6.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/HEART-BEAT%20Sensor",
        type: "arduinoCard",
    },
    {
        id: "24",
        name: "Humidity Sensing",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Humidity%20Sensing%20Using%20Arduino/Images/Fritzing%20Circuit%20Diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Humidity%20Sensing%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "25",
        name: "LCD Color Detector",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/LCD%20Color%20Detector/Circuit-Setup/Circuit.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LCD%20Color%20Detector",
        type: "arduinoCard",
    },
    {
        id: "26",
        name: "LCD Welcome Message",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/LCD%20Welcome%20Message/Images/welcome_message_circuit.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LCD%20Welcome%20Message",
        type: "arduinoCard",
    },
    {
        id: "27",
        name: "LED Activation With Mic in Arduino",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/LED%20Activation%20With%20Mic%20in%20Arduino/Images/led_activation_with_mic_in_arduino.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Activation%20With%20Mic%20in%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "28",
        name: "LED Brightness Control",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/LED%20Brightness%20Control/Gallery/Led-Brightness-Control1.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Brightness%20Control",
        type: "arduinoCard",
    },
    {
        id: "29",
        name: "LED Control using Potentiometer",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/LED%20Control%20using%20Potentiometer/Images/led_control_using_potentiometer.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Control%20using%20Potentiometer",
        type: "arduinoCard",
    },
    {
        id: "30",
        name: "LED Control using Switch",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/LED%20Control%20using%20Switch/Images/led_control_using_switch.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Control%20using%20Switch",
        type: "arduinoCard",
    },
    {
        id: "31",
        name: "Piano",
        image: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Piano%20using%20Arduino/img/Piano.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Piano%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "32",
        name: "Pressure Sensing using BMP280",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Pressure%20Sensing%20using%20BMP280/Images/pressure_sensing_using_BMP280.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Pressure%20Sensing%20using%20BMP280",
        type: "arduinoCard",
    },
    {
        id: "33",
        name: "Printing IR Remote Input On LCD Screen",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Printing%20IR%20Remote%20Input%20On%20LCD%20Screen/images/circuit%20diagram.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Printing%20IR%20Remote%20Input%20On%20LCD%20Screen",
        type: "arduinoCard",
    },
    {
        id: "34",
        name: "Properties Validation of Thermistors",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Properties%20Validation%20of%20Thermistors/Images/properties_validation_of_thermistors.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Properties%20Validation%20of%20Thermistors",
        type: "arduinoCard",
    },
    {
        id: "35",
        name: "RC Car Circuit",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/RC%20Car%20Circuit/Images/Circuit%20Image.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/RC%20Car%20Circuit",
        type: "arduinoCard",
    },
    {
        id: "36",
        name: "RGB LED Scrolling",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/RGB%20LED%20Scrolling/Images/rgb_led_scrolling.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/RGB%20LED%20Scrolling",
        type: "arduinoCard",
    },
    {
        id: "37",
        name: "RGB-LED Brightness controller",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/RGB-LED%20Brightness%20controller/img/img.jpg?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/RGB-LED%20Brightness%20controller",
        type: "arduinoCard",
    },
    {
        id: "38",
        name: "Reading Sensor Data",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Reading%20Sensor%20Data%20using%20Arduino/Images/Circuit%20Image.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Reading%20Sensor%20Data%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "39",
        name: "Record Frequency to SD Card",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Record%20Frequency%20to%20SD%20Card%20using%20Arduino/Images/SS-1.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Record%20Frequency%20to%20SD%20Card%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "40",
        name: "Room Brightness Sensing",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Room%20Brightness%20Sensing%20using%20Arduino/Images/room_brightness_sensing_using_arduino.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Room%20Brightness%20Sensing%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "41",
        name: "Servo Motor Rotation",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Servo%20Motor%20Rotation/Images/ServoMotor_Circuit.PNG?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Servo%20Motor%20Rotation",
        type: "arduinoCard",
    },
    {
        id: "42",
        name: "Smart Street LIght",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Smart%20Street%20LIght/Gallery/street_light.png?raw=true",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Smart%20Street%20LIght",
        type: "arduinoCard",
    },
    {
        id: "43",
        name: "Smoke Detection",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Smoke%20Detection%20Using%20Arduino/Images/smoke_detection_using_arduino.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Smoke%20Detection%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "44",
        name: "Social Distance Detector",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Social%20Distance%20Detector/Images/Circuit-Diagram.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Social%20Distance%20Detector",
        type: "arduinoCard",
    },
    {
        id: "45",
        name: "Speeding Motor",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Speeding%20Motor%20Using%20Arduino/Images/Circuit%20Diagram.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Speeding%20Motor%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "46",
        name: "Storing Sensory Data to SD Card",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Storing%20Sensory%20Data%20to%20SD%20Card/Images/Circuit%20Diagram.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Storing%20Sensory%20Data%20to%20SD%20Card",
        type: "arduinoCard",
    },
    {
        id: "47",
        name: "Temperature Sensing",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Temperature%20Sensing%20using%20Arduino/Images/circuit_diagram.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Temperature%20Sensing%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "48",
        name: "Voltage Sensing",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/Arduino%20Projects/Voltage%20Sensing%20using%20Arduino/Images/SS-1.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Voltage%20Sensing%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "49",
        name: "Basic LED Blink",
        image: "https://github.com/satyamksharma/IoT-Projects-and-Scripts/blob/master/ESP%20Projects/Basic%20LED%20Blink%20using%20ESP32/Images/ESP32-pin-mapping.png?raw=true",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/ESP%20Projects/Basic%20LED%20Blink%20using%20ESP32",
        type: "espCard",
    },
    {
        id: "50",
        name: "Temperature Humidity",
        image: "https://camo.githubusercontent.com/38666061103e5f24bcbe90b813a9e6ce2085487b521dc7064c517a526e8505a8/68747470733a2f2f69302e77702e636f6d2f72616e646f6d6e6572647475746f7269616c732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f30342f6468745f65737033325f62622e706e673f726573697a653d373134253243383932267175616c6974793d3130302673747269703d616c6c2673736c3d31",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/ESP%20Projects/Temperature%20Humidity%20measure%20using%20ESP32",
        type: "espCard",
    },
];
