export const data = [
    {
        id: "1",
        name: "Alarm Clock",
        image: "src/assets/images/AlarmClockusingArduino.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Alarm%20clock%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "2",
        name: "Alternate LED Blinking",
        image: "src/assets/images/alternate_led_blinking.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Alternate%20LED%20Blinking",
        type: "arduinoCard",
    },
    {
        id: "3",
        name: "Automated Hand Sanitizer",
        image: "src/assets/images/Automated-Hand-Sanitizer.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automated%20Hand%20Sanitizer%20Dispenser",
        type: "arduinoCard",
    },
    {
        id: "4",
        name: "Automated Water Pump for Plants",
        image: "src/assets/images/automatedWaterPump.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automated%20Water%20Pump%20for%20Plants",
        type: "arduinoCard",
    },
    {
        id: "5",
        name: "Automatic Door bell",
        image: "src/assets/images/Automatic-Door-Bell.jpg",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automatic%20Door%20Bell",
        type: "arduinoCard",
    },
    {
        id: "6",
        name: "Automatic Fan Speed Control",
        image: "src/assets/images/Automatic-fan-speed-control.jpg",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automatic%20Fan%20Speed%20Control",
        type: "arduinoCard",
    },
    {
        id: "7",
        name: "Automatic Room Temperature Controller",
        image: "src/assets/images/Automatic-Room_temp-controller.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Automatic%20Room%20Temperature%20Controller",
        type: "arduinoCard",
    },
    {
        id: "8",
        name: "Basic LED Blinking",
        image: "src/assets/images/Basic-LED-Blinking.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Basic%20LED%20Blinking%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "9",
        name: "Battery Powered Step Counter",
        image: "src/assets/images/Battery-Powered-Step-Counter.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Battery%20Powered%20Step%20Counter",
        type: "arduinoCard",
    },
    {
        id: "10",
        name: "Burglar Alarm",
        image: "src/assets/images/Burgular-Alarm.jpg",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Burglar%20Alarm",
        type: "arduinoCard",
    },
    {
        id: "11",
        name: "Combination Lock",
        image: "src/assets/images/Combination-Lock.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Combination%20Lock%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "12",
        name: "Controlling DC Motor Using IR Remote",
        image: "src/assets/images/Controlling-DC-motor-UsingIR.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Controlling%20DC%20Motor%20Using%20IR%20Remote",
        type: "arduinoCard",
    },
    {
        id: "13",
        name: "Controlling LED using IR Remote",
        image: "src/assets/images/Controlling-LED-using-IR.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Controlling%20LED%20using%20IR%20Remote",
        type: "arduinoCard",
    },
    {
        id: "14",
        name: "Current Sensor",
        image: "src/assets/images/Current-Sensor.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Current%20Sensor%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "15",
        name: "Dino Game",
        image: "src/assets/images/Dino-game.jpg",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Dino%20Game%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "16",
        name: "Display Time on LCD",
        image: "src/assets/images/Display-Time-on-LCD.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Display%20Time%20on%20LCD%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "17",
        name: "Dual Axis Solar Tracker",
        image: "src/assets/images/Dual-Axis-Solar-Tracker.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Dual%20Axis%20Solar%20Tracker",
        type: "arduinoCard",
    },
    {
        id: "18",
        name: "Electronic Voting Machine",
        image: "src/assets/images/Electronic-Voting-Machine.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Electronic%20Voting%20Machine",
        type: "arduinoCard",
    },
    {
        id: "19",
        name: "Elevator Load Evaluation System",
        image: "",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Elevator%20Load%20Evaluation%20System%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "20",
        name: "Emergency Ventilator",
        image: "src/assets/images/Emergency-Ventilator.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Emergency%20Ventilator",
        type: "arduinoCard",
    },
    {
        id: "21",
        name: "Fire Alarm",
        image: "src/assets/images/Fire-Alarm.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Fire%20Alarm%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "22",
        name: "Gas Leakage Detection",
        image: "src/assets/images/Gas-Leak-Detection.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Gas%20Leakage%20Detection",
        type: "arduinoCard",
    },
    {
        id: "23",
        name: "HEART-BEAT Sensor",
        image: "src/assets/images/Humidity-Seensor.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/HEART-BEAT%20Sensor",
        type: "arduinoCard",
    },
    {
        id: "24",
        name: "Humidity Sensing",
        image: "src/assets/images/Humidity-Seensor.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Humidity%20Sensing%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "25",
        name: "LCD Color Detector",
        image: "src/assets/images/LCD-Color-Detector.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LCD%20Color%20Detector",
        type: "arduinoCard",
    },
    {
        id: "26",
        name: "LCD Welcome Message",
        image: "src/assets/images/LCD-Welcome-Message.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LCD%20Welcome%20Message",
        type: "arduinoCard",
    },
    {
        id: "27",
        name: "LED Activation With Mic in Arduino",
        image: "src/assets/images/LED-Activation-With_MIC.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Activation%20With%20Mic%20in%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "28",
        name: "LED Brightness Control",
        image: "src/assets/images/LED-Brightness-Controller.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Brightness%20Control",
        type: "arduinoCard",
    },
    {
        id: "29",
        name: "LED Control using Potentiometer",
        image: "src/assets/images/LED-control-Using-Potentiometer.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Control%20using%20Potentiometer",
        type: "arduinoCard",
    },
    {
        id: "30",
        name: "LED Control using Switch",
        image: "src/assets/images/LED-control-using-Switch.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/LED%20Control%20using%20Switch",
        type: "arduinoCard",
    },
    {
        id: "31",
        name: "Piano",
        image: "src/assets/images/Pianousing-Arduino.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Piano%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "32",
        name: "Pressure Sensing using BMP280",
        image: "src/assets/images/Pressure-Sensing.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Pressure%20Sensing%20using%20BMP280",
        type: "arduinoCard",
    },
    {
        id: "33",
        name: "Printing IR Remote Input On LCD Screen",
        image: "src/assets/images/Printing-IR-Remote-Input-on-LCD.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Printing%20IR%20Remote%20Input%20On%20LCD%20Screen",
        type: "arduinoCard",
    },
    {
        id: "34",
        name: "Properties Validation of Thermistors",
        image: "src/assets/images/Properties-Validation-Thermoistors.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Properties%20Validation%20of%20Thermistors",
        type: "arduinoCard",
    },
    {
        id: "35",
        name: "RC Car Circuit",
        image: "src/assets/images/RC-Car-Circuit.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/RC%20Car%20Circuit",
        type: "arduinoCard",
    },
    {
        id: "36",
        name: "RGB LED Scrolling",
        image: "src/assets/images/RGB-LED-Scrolling.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/RGB%20LED%20Scrolling",
        type: "arduinoCard",
    },
    {
        id: "37",
        name: "RGB-LED Brightness controller",
        image: "src/assets/images/RGB-LED-Brightness-Control.jpg",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/RGB-LED%20Brightness%20controller",
        type: "arduinoCard",
    },
    {
        id: "38",
        name: "Reading Sensor Data",
        image: "src/assets/images/Reading-Sensor-Data-Using-Arduino.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Reading%20Sensor%20Data%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "39",
        name: "Record Frequency to SD Card",
        image: "src/assets/images/Record-Frequency-To-SD-Card.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Record%20Frequency%20to%20SD%20Card%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "40",
        name: "Room Brightness Sensing",
        image: "src/assets/images/Room-Brightness-Sensing.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Room%20Brightness%20Sensing%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "41",
        name: "Servo Motor Rotation",
        image: "src/assets/images/ServoMotor_Circuit.PNG",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Servo%20Motor%20Rotation",
        type: "arduinoCard",
    },
    {
        id: "42",
        name: "Smart Street LIght",
        image: "src/assets/images/street_light.png",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Smart%20Street%20LIght",
        type: "arduinoCard",
    },
    {
        id: "43",
        name: "Smoke Detection",
        image: "src/assets/images/smoke_detection_using_arduino.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Smoke%20Detection%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "44",
        name: "Social Distance Detector",
        image: "src/assets/images/Social_distance-Detector.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Social%20Distance%20Detector",
        type: "arduinoCard",
    },
    {
        id: "45",
        name: "Speeding Motor",
        image: "src/assets/images/Speeding-Motor.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Speeding%20Motor%20Using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "46",
        name: "Storing Sensory Data to SD Card",
        image: "src/assets/images/Storing-Sensory-Data-SD-Card.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Storing%20Sensory%20Data%20to%20SD%20Card",
        type: "arduinoCard",
    },
    {
        id: "47",
        name: "Temperature Sensing",
        image: "src/assets/images/Temperature-Sensing.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Temperature%20Sensing%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "48",
        name: "Voltage Sensing",
        image: "src/assets/images/Voltage-Sensing.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Voltage%20Sensing%20using%20Arduino",
        type: "arduinoCard",
    },
    {
        id: "49",
        name: "Basic LED Blink",
        image: "src/assets/images/BasicLED-Using-ESP.png",

        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/ESP%20Projects/Basic%20LED%20Blink%20using%20ESP32",
        type: "espCard",
    },
    {
        id: "50",
        name: "Temperature Humidity",
        image: "",
        link: "https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/ESP%20Projects/Temperature%20Humidity%20measure%20using%20ESP32",
        type: "espCard",
    },
];
